In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [3]:
a=np.random.randint(1,100,10)
a

array([82, 93, 11, 27, 86, 40, 50, 21, 35, 78])

In [4]:
a=np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
a=np.arange(1,10)
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a=np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
a=np.random.rand(3,3)
a

array([[0.85445709, 0.14940129, 0.57239005],
       [0.34973655, 0.90948565, 0.1624389 ],
       [0.58801465, 0.22738251, 0.72437207]])

In [8]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [9]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [10]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])